### ISSUE TITLE
👋What's happening!

### ISSUE THREAD

**Issue by VinitGurjar** [TEDxMITUjjain/TEDxMIT-UJJAIN-website#1]
Hi, **@Aayush-Joshi-01** when are you planning to add the event highlights to the site?

**Comment by Aayush-Joshi-01** [comment]
Yeah I was thinking of that, like the gallery and previous video section

**Comment by Aayush-Joshi-01** [comment]
Now that you have mentioned it I'll do that tomorrow probably
